### PR TITLE
Add Usage details to README

### PR DESCRIPTION
**Pull request by benjie**

### CODE REVIEW

**Comment by benjie** [comment]
@tristanpemble I'm _super_ new to ProseMirror, so it's not entirely clear to me how to build the UI around this project to enable tags and mentions.

My current assumption is:

- `onEnter`: show my typeahead (or at least prepare to)
- `onChange`: update (and show) typeahead with updated records for new text
- `onExit`: possibly "accept" the suggestion (if there's a perfect match), otherwise just abort the auto-complete and pass the text through verbatim
- `onKeyPress`: if the key is Enter, Tab or similar then "accept" the current suggestion (if there is one) and `return true`, otherwise pass the event through (`return false`)

My issue is I don't know what "accept" involves? I need to build a mention node and insert it into the prosemirror state somehow, maybe? If there's an example of this that you can point me to, that would be extremely helpful. I'd then be happy to write some of this up into the README (or similar) as I have done here if you like.

As a fellow open-source developer, I seriously appreciate any time you can give me here. 🙏

**Comment by benjie** [comment]
Got it; something like this:

```js
const {
  view,
  text,
  range: { from, to },
} = args;
const label = text.replace(/^@/, "");
const content = schema.nodes.mention.create({
  type: SOMETHING,
  id: SOMETHING,
  label,
});
view.dispatch(
  view.state.tr.replaceWith(from, to, content)
);
```

**Comment by tristanpemble** [comment]
thank you _so much_ for adding some documentation! I will review this for accuracy when I have some time either later today or in the next few days. it's been a while, and I have to do a full context switch to answer your questions as best I can :)

**Comment by benjie** [comment]
Awesome, thanks 🙏

**Comment by tristanpemble** [comment]
Sorry this took so long - your changes look correct, thank you again!

To reiterate what I believe you've already gathered:

Matchers are used to identify when to begin the suggestion. A very basic matcher is included, `triggerCharacter(char)`. This matcher waits for a new word boundary (new line, space, tab, etc) followed by that character. You should be able to write a more advanced matcher that, for example, would autocomplete usernames without typing `@` first.

Your documentation on the event callbacks is spot on.

If I understand what you are asking, I believe the example code you provided would successfully manually insert a "mention" node into the document.

**Review by tristanpemble — APPROVED** [review]

**Pull request merged**
