### PR TITLE
updated to latest prosemirror and split off markdown files

### PR DESCRIPTION
**Pull request by johanneswilm**
Hey, @tristanpemble ! 
Are you still around? I updated your package to work with current prosemirror. I also split off the markdown part into a separate package and renamed it as the prefixing stuff only gave me problems when trying to run it.

Let me know if you want to merge this and continue working on it or whether you'd want me to publish it as a new package.

### CODE REVIEW

**Comment by johanneswilm** [comment]
Hey @tristanpemble , as I didn't hear back from you and really needed this, I went ahead and published to npm as prosemirror-suggestions. I would be very happy to hand package maintainership over to you, so just let me know if you want that.

**Comment by johanneswilm** [comment]
Also, I removed the markdown files. If anyone is using those, I suggest we create a new package for those. You can find those file in the "markdown" dir up until the last commit ( https://github.com/quartzy/prosemirror-suggestions/pull/2/commits/3700417267fb0e608591dc2d3db6430ced3e3896 )

**Review by tristanpemble — COMMENTED** [review]
Hey, I apologize if I was unable to respond in timely manner :)

Moving the markdown pieces out of this repository was definitely a goal when written, so I'm happy to see you submitted a PR to help! 

Unfortunately, at the moment, this PR appears to do a lot at once; I think you created it off of your fork's master branch instead of a feature branch, so the changes you have made to republish the package under the global NPM namespace are showing up here.

As a result, it is difficult for me to review your changes as is. If you could update this PR to limit its scope, or close and resubmit separate PRs, that would be great!

**Comment by johanneswilm** [comment]
Hey,

yeah, so I didn't understand a lot of what was going on as this was written fro PM 0.24(?). I updated it to the latest PM and latest transpiler, etc. and just made sure it worked. In many cases I just spent some hours trying it out without really understanding what was happening in the old code. It was showing up errors with the transpiler as well, so I couldn't easily go back in time to see how it used to work.

I'm sorry, but that's the reason I can only offer you this entire thing as is and I don't think I can split up into individual feature branches.

There is a new package for the changed version on npmjs now. I will be happy to transfer maintainership to you if you want to keep updating it.

Other than that, I'm really happy about how it is working now. I may be fixing individual bugs still as I come across them.

**Comment by johanneswilm** [comment]
PS: And yes I realize that some of my changes likely aren't really needed. I just worked with a limited time budget and for example wasn't sure if the code of conduct charter applied to non-PM-core packages. The fact that there was another PR from April made me think that maybe you were no longer interested in this. So I took a chance... and apparently I was wrong.

I think the easiest is if you want to go back to maintaining it and keeping it up to date with PM is if you go through the changes I made and see what makes sense and what doesn't. The extra options I needed to add, as there seemed to be no way of exiting the suggestions mechanism under certain situations.

Again, sorry for that.

**Comment by tristanpemble** [comment]
Specifically, I cannot accept this PR with the changes you have made to the license, code of conduct, test configuration and package metadata. If you are able to revert those changes so that the PR is limited to code changes, I'd be happy to review the code from there.

**Comment by johanneswilm** [comment]
Hey,
as for the license - I cannot really change that. I am in Sweden and copyright assignment is not legally possible here and in most of Europe. So whether I want it or not, I cannot give away my copyright. Really sorry about that, but that's just legal stuff.

I'm of course OK, with you reverting those other things if you can get the tests to work again that way. 

Otherwise, if you cannot merge the PR, that's totally understandable. I'm ok with maintaining this as a fork in that case.

**Comment by tristanpemble** [comment]
I've [updated the ProseMirror packages](https://github.com/quartzy/prosemirror-suggestions/pull/3). I also made sure that CircleCI is running tests on Node v10.8, just to make sure that wasn't an issue. All the tests [seem to still pass](https://circleci.com/gh/quartzy/prosemirror-suggestions/tree/master), and a quick run through of the example application yielded no obvious issues.

- I've noticed in your PR that you switched from Yarn to NPM. We use Yarn at Quartzy.
- I also noticed you moved the ProseMirror packages as direct dependencies of the plugin, which is an anti-pattern, [as outlined in this blog post](https://nodejs.org/en/blog/npm/peer-dependencies/).
- I wasn't familiar with what you said regarding licensing and copyright, so I [checked](https://github.com/facebook/react/blob/master/LICENSE) [out](https://github.com/rollup/rollup/blob/master/LICENSE.md) [the](https://github.com/google/closure-library/blob/master/LICENSE) [licenses](https://github.com/emberjs/ember.js/blob/master/LICENSE) for several other projects, including [ProseMirror](https://github.com/ProseMirror/prosemirror/blob/master/LICENSE), and it does not seem like a normal practice to add a line of attribution for every contributor. I am open to discussing what would be necessary to accept contributions from anyone who is willing and able to contribute. I would have to discuss those changes with the appropriate people at my company, however. I think the simplest and most common solution is to add an attribution to all contributors with a link to the GitHub contributors page. I see you removed our similar, existing attribution, from the README in this PR.
- Removing the code of conduct from the project will not be considered under any circumstances.

I'm happy to discuss the feature you'd like for your project -- from what I gather it seems related to configuring the keyboard shortcuts for escaping. If you could kindly open an issue that describes the problem you ran into, and what changes you would like to see, we can discuss whether a bug needs to be addressed, or if there is a feature that should be built. That way we can work together on making sure it fits both your use case and the direction of this project.

Don't be concerned that this repository is unmaintained. This project has been actively used in production for nearing one year by tens of thousands of scientists daily. We just haven't really had to make any adjustments to it since it was released, which is why there has not been any recent activity.

In the meantime, you should be able to reference your fork [directly in your package.json](https://docs.npmjs.com/files/package.json#github-urls) without publishing a fork of this repository directly onto NPM.  I would greatly appreciate it if you did hand over the package you published, it would be best to reduce confusion for plugin users, and focus our efforts on improving this plugin 🙂

**Comment by johanneswilm** [comment]
Hey,
not everyone is familiar with the different European copyright laws. But even if they put an incorrect copyright notice, the copyright still follows those. Marijn, living in Germany, cannot give his copyright away, for example. That's just how copyright laws work here. This is the main reason why they make CLAs.

As I said initially, I'll happily hand over the package to you if you are willing to keep it up to date with current PM for the forseeable future. As for yarn and npm and all that - sure, as long as you can get it to work and it has all the features required, I'm ok with anything. I removed those other files believing I would have to maintain this as a package, so you can just readd them if you want to do it. I just didn't have the time to try that out, and it looked like you had stopped maintaining the package as it had not been updated for several PM releases.

I don't have much more time for this right now and the package is working as is for me. Let me know when you have it updated on your side to use your tools again and I'll hand you control over of the package.

Thanks again for the package!

**Comment by johanneswilm** [comment]
@tristanpemble One last thing about those dependencies: Your package gave me problems as you had listed `prosemirror-markdown` as a peer dependency, but then you were importing directly from that package, which meant that it threw errors here. And the dependency versions were not working. So at least for that package, it didn't seem like the plugin case really applied - it was just a regular dependency. If you don't import anything from the other packages, maybe they are indeed better listed as peer dependencies.

Another issue was that of escaping from the tagger. I tried to look at some other online word processors and how one can escape there. The arrow keys, and Escape seem to do that. Despite my additions, one thing I still could not figure out was how to escape from the tagger if spaces are allowed. Basically if I type anything in that same paragraph somewhere beyond the @-symbol, it restarts the tagger. The online word processor I looked at simple doesn't allow spaces. So I figured that's good enough for our usecase. But I really don't know how one would use this with allowing spaces.

**Comment by johanneswilm** [comment]
One more thing I remember about prosemirror-markdown. When I first installed your package, it gave me the warnings during npm install due to the peer dependencies. I ignored them at first. When I then tried importing it, it gave me a warning about missing prosemirror-markdown. 

One of the first things I then tried was to also install prosemirror-markdown, even though I don't use it in my own code, in hope that this would make the warning go away. Unfortunately, I still received the same error about prosemirror-markdown not being present. At that stage I forked and made a separate package (which grew into this PR). Maybe there is some way to salvage the peer dependency stuff, but I don't know how and I didn't have the time to figure it out. That's why it's just normal dependencies in the fork. And they happen to work with current PM.

**Comment by johanneswilm** [comment]
As for the license: I see Marijn mentioned a simple "and others" to show that there are other copyright holders as well. That seems like a fine way of doing it. As I said earlier, the copyright is held by the various authors if they are in the relevant European countries, no matter whether that file mentions them or not. If it doesn't mention them, then it's simply displaying incorrect information.

**Comment by johanneswilm** [comment]
Ok, closing this as you don't seem to be interested. But feel free to contact me should you want to merge in the future.

**Comment by tristanpemble** [comment]
I do not work on weekends. I apologize that two days is longer than you'd like to wait to hear back from a low throughput open source project maintainer. Thank you for the time you spent on this pull request.

**Comment by johanneswilm** [comment]
Hey Tristan,
sometimes the tone of voice of a message like this doesn't transport well over the internet.. But I really just meant what I said, that it sounded like you weren't interested. And that is fine. I currently depend on my version of the library for two different projects, and I need the additions that I made. I may even have to do more things based on user feedback. As long as the license of my fork stays the same, you are of course always welcome to pick parts of or the entire code of the version I maintain. I added a link to the readme making it very clear where the code came from, just in case someone shouldn't check the copyright files, etc. .

**Pull request closed without merging**
